### ISSUE TITLE
Is there possibility to update Test report after some time? 

### ISSUE THREAD

**Issue by lubshilk** [Top-Q/difido-reports#154] opened 2017-08-27 11:32 UTC
Hi,
It's not issue, it's a question:
1. Is it possible to receive TC ID from Difido server?
2. Is it possible to update TC result on Difido server using this ID after some time (up to 4 hours after it was firstly reported)?

Explanation:
We have many scenarios like:
TC1 - send SMS/mail or call from application - this should be reported to some DB
TC2 - some verification on recipient side
TC3 - DB verification

Our problem: DB is updated sometimes after more than hour. We'd like to execute DB verification as separate system and save the result to reports on Difido server as part of the described above scenario. If it is possible, TC3 will just save/send  all needed data to separate application/system for further execution

Thank you in advance for inforamation/suggestion

**Comment by itaiag** [comment] 2017-08-29 12:42
Hi.
Let's see.

1. Unfortunately, no. The execution id is received from the server and the TC id is generated in the client but it is not exposed outside the class. 
1. No. once the execution is ended and marked as none active, you are not suppose to add any more data to the tests. 

One way to solve the problem is to change the [max.execution.idle.time.in.seconds](https://github.com/Top-Q/difido-reports/wiki/Server-Configuration) property to a very large number to make sure that the execution will not end too soon and then use the [server api](https://github.com/Top-Q/difido-reports/wiki/Server-API) to handle the executions by yourself. Meaning, starting and ending the execution externally and not from JSystem.
Notice that you will also need to pass the execution id to JSystem in the [*difido.properties*](https://github.com/Top-Q/difido-reports/wiki/Client-Configuration) and set the execution to shared as seen in [this example](https://github.com/Top-Q/difido-reports/wiki/Client-Configuration#appendtoexistingexecution-and-existingexecutionid)

It's not an easy solution but it can do the trick.

**Closed** 2017-09-11 07:05 UTC
Labels: question

**Comment by lubshilk** [comment] 2017-09-11 07:21
Sorry for late reply, was on another project :)
Thank you for suggestion. We'll try to execute it
