### ISSUE TITLE
The Year/Day Inserted is Incorrect

### ISSUE THREAD

**Issue by NirBY** [Top-Q/difido-reports#171] opened 2017-10-24 14:48 UTC
**The configuration used**:
Number of the Machines used (jSystem) = 7
Difido Server ver: 2.1.00
Kibana ver: 5.0.1

**In some executions the date inserted is incorrect**:
![image](https://user-images.githubusercontent.com/9214815/31949888-093000a0-b8e3-11e7-80b9-831128bb6b3d.png)

**It also seems that the date show correctly in status bar page**:
![image](https://user-images.githubusercontent.com/9214815/31949951-379e0f5e-b8e3-11e7-8a82-32a3d9d508c1.png)

**Nothing in the log**:
root@linux:~# cat /usr/local/bin/difido-server/log/difido* | grep "79063"
2017-10-23 02:40:24.166 DEBUG 1738 --- [.92-8088-exec-8] i.c.t.report.front.rest.MachineResource  : POST - Add new machine to execution 79063
2017-10-23 02:40:24.988 DEBUG 1738 --- [.92-8088-exec-6] i.c.t.report.front.rest.MachineResource  : PUT - Update machine to execution with id 79063
2017-10-23 02:40:25.351 DEBUG 1738 --- [.92-8088-exec-3] i.c.t.report.front.rest.MachineResource  : PUT - Update machine to execution with id 79063
2017-10-23 02:40:25.685 DEBUG 1738 --- [.92-8088-exec-4] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:25.827 DEBUG 1738 --- [.92-8088-exec-5] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:25.858 DEBUG 1738 --- [.92-8088-exec-7] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:25.922 DEBUG 1738 --- [.92-8088-exec-1] i.c.t.report.front.rest.MachineResource  : PUT - Update machine to execution with id 79063
2017-10-23 02:40:26.503 DEBUG 1738 --- [.92-8088-exec-8] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:26.628 DEBUG 1738 --- [.92-8088-exec-2] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:26.692 DEBUG 1738 --- [.92-8088-exec-9] i.c.t.r.front.rest.FileUploadResource    : POST - Attach file 'file' to test with uid 4871508715657-2 in execution 79063
2017-10-23 02:40:26.813 DEBUG 1738 --- [.92-8088-exec-6] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:26.829 DEBUG 1738 --- [.92-8088-exec-3] i.c.t.r.front.rest.FileUploadResource    : POST - Attach file 'file' to test with uid 4871508715657-2 in execution 79063
2017-10-23 02:40:26.844 DEBUG 1738 --- [.92-8088-exec-4] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:26.875 DEBUG 1738 --- [.92-8088-exec-5] i.c.t.report.front.rest.MachineResource  : PUT - Update machine to execution with id 79063
2017-10-23 02:40:27.485 DEBUG 1738 --- [.92-8088-exec-7] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:27.562 DEBUG 1738 --- [.92-8088-exec-1] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:27.594 DEBUG 1738 --- [92-8088-exec-10] i.c.t.r.front.rest.FileUploadResource    : POST - Attach file 'file' to test with uid 4871508715657-3 in execution 79063
2017-10-23 02:40:27.719 DEBUG 1738 --- [.92-8088-exec-8] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:27.735 DEBUG 1738 --- [.92-8088-exec-2] i.c.t.r.front.rest.FileUploadResource    : POST - Attach file 'file' to test with uid 4871508715657-3 in execution 79063
2017-10-23 02:40:27.752 DEBUG 1738 --- [.92-8088-exec-9] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:27.781 DEBUG 1738 --- [.92-8088-exec-3] i.c.t.report.front.rest.MachineResource  : PUT - Update machine to execution with id 79063
2017-10-23 02:40:28.235 DEBUG 1738 --- [.92-8088-exec-4] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:28.297 DEBUG 1738 --- [.92-8088-exec-5] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:29.188 DEBUG 1738 --- [.92-8088-exec-7] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:29.313 DEBUG 1738 --- [.92-8088-exec-1] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:59.398 DEBUG 1738 --- [.92-8088-exec-1] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:59.620 DEBUG 1738 --- [.92-8088-exec-2] i.c.t.r.front.rest.FileUploadResource    : POST - Attach file 'file' to test with uid 4871508715657-4 in execution 79063
2017-10-23 02:40:59.632 DEBUG 1738 --- [.92-8088-exec-9] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:59.652 DEBUG 1738 --- [.92-8088-exec-6] i.c.t.r.front.rest.FileUploadResource    : POST - Attach file 'file' to test with uid 4871508715657-4 in execution 79063
2017-10-23 02:40:59.666 DEBUG 1738 --- [.92-8088-exec-3] i.c.t.r.front.rest.FileUploadResource    : POST - Attach file 'file' to test with uid 4871508715657-4 in execution 79063
2017-10-23 02:40:59.711 DEBUG 1738 --- [.92-8088-exec-4] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:40:59.758 DEBUG 1738 --- [.92-8088-exec-5] i.c.t.report.front.rest.MachineResource  : PUT - Update machine to execution with id 79063
2017-10-23 02:41:00.460 DEBUG 1738 --- [.92-8088-exec-1] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:41:00.491 DEBUG 1738 --- [92-8088-exec-10] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:41:01.067  WARN 1738 --- [ncActionQueue-1] i.c.t.r.b.html.HtmlReportsController     : Failed to create new file /usr/local/bin/difido-server/docRoot/reports/exec_79063/tests/test_4871508715657-4/sip0797087258.log
2017-10-23 02:41:01.600 DEBUG 1738 --- [.92-8088-exec-9] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:41:01.618 DEBUG 1738 --- [.92-8088-exec-6] i.c.t.r.front.rest.FileUploadResource    : POST - Attach file 'file' to test with uid 4871508715657-5 in execution 79063
2017-10-23 02:41:01.632 DEBUG 1738 --- [.92-8088-exec-3] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:41:01.663 DEBUG 1738 --- [.92-8088-exec-4] i.c.t.report.front.rest.MachineResource  : PUT - Update machine to execution with id 79063
2017-10-23 02:41:01.991 DEBUG 1738 --- [.92-8088-exec-7] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:41:02.022 DEBUG 1738 --- [.92-8088-exec-5] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:41:03.476 DEBUG 1738 --- [.92-8088-exec-8] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:41:03.497 DEBUG 1738 --- [.92-8088-exec-2] i.c.t.r.front.rest.FileUploadResource    : POST - Attach file 'file' to test with uid 4871508715657-6 in execution 79063
2017-10-23 02:41:03.523 DEBUG 1738 --- [.92-8088-exec-9] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 79063
2017-10-23 02:41:03.539 DEBUG 1738 --- [.92-8088-exec-6] i.c.t.report.front.rest.MachineResource  : PUT - Update machine to execution with id 79063
2017-10-23 02:41:04.257 DEBUG 1738 --- [.92-8088-exec-3] i.c.t.r.front.rest.ExecutionResource     : PUT - Upating execution with id 79063. to active: false and locked: null
2017-10-23 02:41:04.258 DEBUG 1738 --- [.92-8088-exec-3] i.c.t.r.b.plugins.PluginController       : Plugin controller was called at the end of execution 79063

**Comment by NirBY** [comment] 2017-10-24 15:00
**It also causing for Error in log (When stating server)**:
2017-10-24 17:58:21.207 ERROR 15295 --- [pool-4-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.time.format.DateTimeParseException: Text '00/10/2017' could not be parsed: Invalid value for DayOfMonth (valid values 1 - 28/31): 0
        at java.time.format.DateTimeFormatter.createError(DateTimeFormatter.java:1920) ~[na:1.8.0_91]
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1855) ~[na:1.8.0_91]
        at java.time.LocalDate.parse(LocalDate.java:400) ~[na:1.8.0_91]
        at il.co.topq.report.front.scheduled.HtmlReportsEraser.eraseOldHtmlReports(HtmlReportsEraser.java:58) ~[difido-server.jar!/:2.1.00]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_91]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: java.time.DateTimeException: Invalid value for DayOfMonth (valid values 1 - 28/31): 0
        at java.time.temporal.ValueRange.checkValidIntValue(ValueRange.java:330) ~[na:1.8.0_91]
        at java.time.temporal.ChronoField.checkValidIntValue(ChronoField.java:722) ~[na:1.8.0_91]
        at java.time.chrono.IsoChronology.resolveYMD(IsoChronology.java:551) ~[na:1.8.0_91]
        at java.time.chrono.IsoChronology.resolveYMD(IsoChronology.java:123) ~[na:1.8.0_91]
        at java.time.chrono.AbstractChronology.resolveDate(AbstractChronology.java:472) ~[na:1.8.0_91]
        at java.time.chrono.IsoChronology.resolveDate(IsoChronology.java:492) ~[na:1.8.0_91]
        at java.time.chrono.IsoChronology.resolveDate(IsoChronology.java:123) ~[na:1.8.0_91]
        at java.time.format.Parsed.resolveDateFields(Parsed.java:351) ~[na:1.8.0_91]
        at java.time.format.Parsed.resolveFields(Parsed.java:257) ~[na:1.8.0_91]
        at java.time.format.Parsed.resolve(Parsed.java:244) ~[na:1.8.0_91]
        at java.time.format.DateTimeParseContext.toResolved(DateTimeParseContext.java:331) ~[na:1.8.0_91]
        at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1955) ~[na:1.8.0_91]
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851) ~[na:1.8.0_91]
        ... 15 common frames omitted

**Comment by itaiag** [comment] 2017-12-29 09:58
There is a good chance that this issue is caused by issue #179 . I am closing this issue, but it will be reopened if the issue is reproduced after the fix of #179  is merged to the master branch.

**Closed by itaiag** 2017-12-29 09:58 UTC
