### ISSUE TITLE
Difido server stuck & Some of the tests does not have data

### ISSUE THREAD

**Issue by NirBY** [Top-Q/difido-reports#152] opened 2017-08-22 05:57 UTC
**The configuration used**:
1. Difido configuration attached:
[difido_config.zip](https://github.com/Top-Q/difido-reports/files/1240921/difido_config.zip)
2. Number of the Machines used (jSystem) = 7
3. Difido Server ver: 2.1.00
4. Kibana ver: 5.0.1

**How I solved it**:
Restart Difido Server.

**In some of the cases getting an error when try to open the report**:
![image](https://user-images.githubusercontent.com/9214815/29550591-2d7e41ea-8717-11e7-9254-dc4575075395.png)

**The Difido log**:
[difido.log.zip](https://github.com/Top-Q/difido-reports/files/1240952/difido.log.zip)

**Exception in the log**:

> 2017-08-22 03:04:03.695 DEBUG 32257 --- [.92-8088-exec-6] i.c.t.r.front.rest.TestDetailsResource   : POST - Add execution details to execution with id 29910
2017-08-22 03:04:03.726 ERROR 32257 --- [.92-8088-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [org.springframework.core.task.TaskRejectedException: Executor [java.util.concurrent.ThreadPoolExecutor@37acfdaa[Running, pool size = 1, active threads = 1, queued tasks = 10000, completed tasks = 1786791]] did not accept task: org.springframework.aop.interceptor.AsyncExecutionInterceptor$1@3dca1389] with root cause

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@283ac0d8 rejected from java.util.concurrent.ThreadPoolExecutor@37acfdaa[Running, pool size = 1, active threads = 1, queued tasks = 10000, completed tasks = 1786791]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) ~[na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) [na:1.8.0_91]

**Comment by itaiag** [comment] 2017-12-29 10:11
We are unable to reproduce this issue so I am closing it for now. If it is reproduced again in your environment, or, better yet, you can add steps to reproduce, I will reopen it.

**Closed by itaiag** 2017-12-29 10:11 UTC
Labels: bug
